#!/bin/bash
# System Information Report

echo "System Report for $(hostname) generated by $USER, on $(date)"
echo ""
echo "System Information"
echo "-----------------------"
#gives you the Distro Name and Version
source /etc/os-release
echo "OS: $PRETTY_NAME"
#gives you the Uptime
echo "Uptime: $(uptime -p)"
#gets the CPU's Processor Make and Model
cpuInfo=$(lscpu | grep "Model name")
cpuInfo=${cpuInfo#*: }
echo "CPU: $cpuInfo"
#gets the SIZE OF INSTALLED RAM
echo "RAM: $(( $(grep MemTotal /proc/meminfo | grep -o '[0-9]*') / 1024 / 1024 )) GB"
#gives you the Make and Model and Size for all the installed disks 
echo "Disk(s):"
lsblk -d -o NAME,MODEL,SIZE | grep "^sd"
#gets you the Make and Model of the video card
echo "Video: $(lspci | grep VGA)"
#gets the IP Address for the interface thats connected to the default gateway
echo "Host Address:"
ip route | grep default
ip addr show ens33
#gets you the Default Gateway Adress
echo "Gateway IP:"
ip route | grep default
gateway=$(ip route | grep default)
set -- $gateway
echo "Gateway IP:" $3
#gets you the IP of the DNS server
echo "DNS Server:"
grep nameserver /etc/resolv.conf
echo ""
echo "System Status"
echo "-----------------------"
#Users that are Logged In
echo "Users Logged In:"
users
#gets the free disk space
echo "Disk Space:"
df -h
#gives the Process Count
echo "Process Count: $(ps -e | wc -l)"
#give the Load Averages
echo "Load Averages: $(cat /proc/loadavg | awk '{print $1", "$2", "$3}')"
#shows the Listening Network Ports
echo "Listening Network Ports:"
ss -tuln | grep LISTEN
#gives UFW Status
echo "UFW Status:"
sudo ufw status
echo ""
echo "---- End of Report ----"
