#!/bin/bash
# System Information Report

echo "System Report for $(hostname) generated by $USER, on $(date)"
echo ""
echo "System Information"
echo "-----------------------"
source /etc/os-release
echo "OS: $PRETTY_NAME"
echo "Uptime: $(uptime -p)"
cpuInfo=$(lscpu | grep "Model name")
cpuInfo=${cpuInfo#*: }
echo "CPU: $cpuInfo"
echo "RAM: $(( $(grep MemTotal /proc/meminfo | grep -o '[0-9]*') / 1024 / 1024 )) GB"


