#!/bin/bash
# System Information Report

echo "System Report for $(hostname) generated by $USER, on $(date)"
echo ""
echo "System Information"
echo "-----------------------"
source /etc/os-release
echo "OS: $PRETTY_NAME"
echo "Uptime: $(uptime -p)"
cpuInfo=$(lscpu | grep "Model name")
cpuInfo=${cpuInfo#*: }
echo "CPU: $cpuInfo"
echo "RAM: $(( $(grep MemTotal /proc/meminfo | grep -o '[0-9]*') / 1024 / 1024 )) GB"
echo "Disk(s):"
lsblk -d -o NAME,MODEL,SIZE | grep "^sd"
echo "Video: $(lspci | grep VGA)"
echo "Host Address:"
ip route | grep default
ip addr show ens33
echo "Gateway IP:"
ip route | grep default
gateway=$(ip route | grep default)
set -- $gateway
echo "Gateway IP:" $3
echo "DNS Server:"
grep nameserver /etc/resolv.conf
echo ""
echo "System Status"
echo "-----------------------"
echo "Users Logged In:"
users
echo "Disk Space:"
df -h
echo "Process Count: $(ps -e | wc -l)"
echo "Load Averages: $(cat /proc/loadavg | awk '{print $1", "$2", "$3}')"
echo "Listening Network Ports:"
ss -tuln | grep LISTEN
echo "UFW Status:"
sudo ufw status
echo ""
echo "---- End of Report ----"
